### ISSUE TITLE
how do u run the bot?

### ISSUE THREAD

**Issue by nososho** [TheTurkeyDev/Discord-Games#14]
how do u run the bot? thanks

**Comment by itsjusttriz** [comment]
Try `npm run run`

**Comment by nososho** [comment]
> Try `npm run run`

it sends this error:

` npm run run

> discord-games-bot@1.0.0 run /home/runner/g4mes
> npx tsc & node .

internal/modules/cjs/loader.js:303
      throw err;
      ^

Error: Cannot find module '/home/runner/g4mes/output/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:295:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:508:18)
    at resolveMainPath (internal/modules/run_main.js:12:25)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:54:24)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  path: '/home/runner/g4mes/package.json',
  requestPath: '/home/runner/g4mes'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-games-bot@1.0.0 run: `npx tsc & node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the discord-games-bot@1.0.0 run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-06-08T23_16_38_951Z-debug.log
exit status 1`

**Comment by itsjusttriz** [comment]
inside your `package.json`, try changing `&` to `&&` on the line that says `npx tsc & node .`and see if it works?

**Comment by TheTurkeyDev** [comment]
Closing for inactivity
